# Generated by Django 2.0.4 on 2020-06-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='player_picture',
            new_name='image_uri',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='name',
        ),
    ]
